---
title: "Class 08: Chicago Crime Data"
author: "Taylor Arnold"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(fig.path = "../assets/2017-09-21-class08/")
```

```{r, message = FALSE}
library(readr)
library(ggplot2)
library(dplyr)
```


```{r, message = FALSE}
crimes <- read_csv("~/files/ml_data/chi_crimes_3.csv")
```

```{r}
temp <- crimes[crimes$crime_type %in% c("theft", "narcotics"),]
temp$y <- as.numeric(temp$crime_type == "theft")
model <- lm(y ~ latitude + longitude,
            data = temp, subset = train_id == "train")
temp$y_pred <- predict(model, newdata = temp)
```

```{r, message = FALSE}
library(ggmap)
qmplot(longitude, latitude, data = temp, color = factor(y_pred > 0.5)) +
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r, message = FALSE}
model <- lm(y ~ poly(latitude, 4) + poly(longitude, 4),
            data = temp, subset = train_id == "train")
temp$y_pred <- predict(model, newdata = temp)
qmplot(longitude, latitude, data = temp, color = factor(y_pred > 0.5)) +
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r, message = FALSE}
library(FNN)
X <- scale(as.matrix(select(temp, longitude, latitude)))
y <- temp$y
X_train <- X[temp$train_id == "train",]
y_train <- y[temp$train_id == "train"]

temp$y_pred <- as.numeric(FNN::knn(train = X_train, test = X, cl = y_train, k = 200))

qmplot(longitude, latitude, data = temp, color = factor(y_pred)) +
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r, message = FALSE}
crimes$y <- as.numeric(factor(crimes$crime_type))


library(FNN)
X <- scale(as.matrix(select(crimes, longitude, latitude)))
y <- crimes$y
X_train <- X[crimes$train_id == "train",]
y_train <- y[crimes$train_id == "train"]

crimes$y_pred <- as.numeric(FNN::knn(train = X_train, test = X, cl = y_train, k = 500))

qmplot(longitude, latitude, data = crimes, color = factor(y_pred)) +
  viridis::scale_color_viridis(discrete = TRUE)
```



```{r, message = FALSE, warning = FALSE}
library(nnet)
library(ggmap)
library(smodels)
crimes$h6 <- as.numeric(cut(crimes$hour, 6, label = FALSE))
model <- multinom(crime_type ~ poly(longitude, latitude, h6, degree = 3),
                  data = crimes)
crimes$y_pred <- predict(model, newdata = crimes)
qplot(longitude, latitude, data = crimes, color = factor(y_pred)) +
  viridis::scale_color_viridis(discrete = TRUE) +
  facet_wrap(~h6)
```







