---
title: "Class 03: The Lady Tasting Tea"
author: "Taylor Arnold"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(fig.path = "../assets/2017-09-04-class03/")
```

```{r, message = FALSE}
library(readr)
library(ggplot2)
library(dplyr)
```

## tea

```{r, message = FALSE}
tea <- read_csv("~/files/ml_data/tea.csv")
```


```{r, warning=FALSE}
qplot(num_reviews, score, data = tea)
```

```{r, warning=FALSE}
qplot(num_reviews, score, data = tea) +
  geom_smooth(method = "lm")
```


$$ \text{mean} (Y_i) = \alpha + \beta * X_i $$


$$ Y_i = \alpha + \beta * X_i + \epsilon_i, \quad mean(\epsilon_i) = 0 $$


$$ \alpha, \beta \in \arg\min \left\{ \left. \sum_i \left(y_i - a - b x_i \right)^2 \quad \right| \quad a, b \in \mathbb{R} \right\} $$


```{r, warning = FALSE}
tea$score_pred <- 89 + tea$num_reviews * 0.002
qplot(num_reviews, score, data = tea) +
  geom_line(aes(num_reviews, score_pred), color = "orange") +
  geom_segment(aes(xend = num_reviews, yend = score_pred), alpha = 0.5)
```




```{r, warning = FALSE}
model <- lm(score ~ num_reviews, data = tea)
model
```

```{r}
summary(model)
```

```{r}
tea$score_pred <- predict(model, newdata = tea)
```


```{r, warning=FALSE}
qplot(num_reviews, score, data = tea) +
  geom_point(aes(num_reviews, score_pred), color = "orange")
```


```{r, warning=FALSE}
sqrt(mean((tea$score - tea$score_pred)^2, na.rm = TRUE))
```


```{r, warning=FALSE}
sqrt(mean((tea$score - mean(tea$score, na.rm = TRUE))^2, na.rm = TRUE))
```

```{r}
table(tea$train_id)
```


```{r}
model <- lm(score ~ num_reviews, data = tea,
            subset = train_id == "train")
tea$score_pred <- predict(model, newdata = tea)
model
```

```{r}
sqrt(tapply((tea$score - tea$score_pred)^2, tea$train_id, mean))
```

$$ Y_i = \alpha + \beta * X_i + \gamma * Z_i + \epsilon_i, \quad mean(\epsilon_i) = 0 $$


```{r}
model <- lm(score ~ num_reviews + price, data = tea,
            subset = train_id == "train")
tea$score_pred <- predict(model, newdata = tea)
model
```

```{r}
sqrt(tapply((tea$score - tea$score_pred)^2, tea$train_id, mean))
```

```{r}
tea$num_reviews_square <- tea$num_reviews^2
model <- lm(score ~ num_reviews + num_reviews_square,
            data = tea,
            subset = train_id == "train")
tea$score_pred <- predict(model, newdata = tea)
model
```

```{r}
sqrt(tapply((tea$score - tea$score_pred)^2, tea$train_id, mean))
```

```{r}
tea$is_masters <- as.numeric(tea$type == "masters")
model <- lm(score ~ num_reviews + is_masters,
            data = tea,
            subset = train_id == "train")
tea$score_pred <- predict(model, newdata = tea)
model
```

```{r}
sqrt(tapply((tea$score - tea$score_pred)^2, tea$train_id, mean))
```


```{r, warning=FALSE}
qplot(num_reviews, score, data = tea) +
  geom_point(aes(num_reviews, score_pred), color = "orange")
```


```{r}
submit <- select(tea, obs_id, score_pred)
write_csv(submit, "class02_submit.csv")
```

NOTES: Brute force algorithm for OLS?